# Site settings
baseURL = "//www.alexflint.io"
languageCode = "en-US"
title = "Alex Flint"
theme = "split"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-36566659-4"

# Copyright
copyright = "&copy;2019 Alex Flint"

[params]

  # Metadata for search engines and social sharing
  author = "Alex Flint"
  description = "Roboticist. Paraglider. Wannabe cosmic adventurer."
  shareImage = "images/social.jpg"
  twitterHandle = "alexjflint"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Contact"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:alex.flint@gmail.com"

      [[params.links.list1.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/alexjflint/"

      [[params.links.list1.link]]
        text = "Facebook"
        url = "https://www.facebook.com/alex.j.flint"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Creations"

      [[params.links.list2.link]]
        text = "Github"
        url = "https://github.com/alexflint"

      [[params.links.list2.link]]
        text = "Blog"
        url = "https://medium.com/@alexjflint"

      [[params.links.list2.link]]
        text = "Publications"
        url = "https://scholar.google.com/citations?user=D-McqBkAAAAJ&hl=en"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Other"

      [[params.links.list3.link]]
        text = "AngelList"
        url = "https://angel.co/alex-flint"

      [[params.links.list3.link]]
        text = "Crunchbase"
        url = "https://www.crunchbase.com/person/alex-flint"

      [[params.links.list3.link]]
        text = "Twitter"
        url = "https://twitter.com/alexjflint"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
